version: '3.9'
services:

  redis:
    image: redis:latest
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  api:
    build:
      context: ./
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - 8080:8080
